# Generated by Django 4.1.2 on 2022-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('imagen', models.ImageField(null=True, upload_to='carpeta de imagenes', verbose_name='Imagen')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('genero', models.CharField(max_length=100, verbose_name='genero')),
                ('fechaN', models.CharField(max_length=100, verbose_name='fecha de nacimiento')),
                ('tipoUsuarioID', models.CharField(max_length=100, verbose_name='tipoUsuarioID')),
                ('login', models.CharField(max_length=100, verbose_name='login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('usuarioStatus', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
    ]
