# Generated by Django 4.1.2 on 2022-10-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('puntoID', models.AutoField(primary_key=True, serialize=False)),
                ('puntoNombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('puntoDir', models.CharField(max_length=100, verbose_name='Dirección')),
                ('url', models.ImageField(null=True, upload_to='carpeta de imagenes', verbose_name='Imagen')),
                ('puntoRef', models.CharField(max_length=100, verbose_name='Referencia de dirección')),
                ('puntoCol', models.CharField(max_length=100, verbose_name='Colonia')),
                ('puntoCP', models.CharField(max_length=100, verbose_name='Código postal')),
                ('puntoLocalidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('puntoInfromacion', models.TextField(max_length=100, verbose_name='Información')),
                ('puntoHorario', models.CharField(max_length=100, verbose_name='Horario')),
                ('puntoNumVisitas', models.CharField(max_length=100, verbose_name='Número de visitas')),
                ('puntoCatID', models.CharField(max_length=100, verbose_name='Categoría')),
                ('puntoObsverv', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('puntoStatus', models.CharField(max_length=100, verbose_name='Estatus')),
            ],
        ),
    ]
